### PR TITLE
add quick start to readme

### PR DESCRIPTION
**Pull request by visr**
I always like to have a little quick start to see the package in action. Feel free to edit.

### CODE REVIEW

**Review by rafaqz — COMMENTED** [review]
Looks good, just add that its also used in DimensionalData.jl

**Comment by visr** [comment]
Shall we merge this?

**Comment by rafaqz** [comment]
Yes, completely forgot

**Comment by visr** [comment]
I can't merge it :)

**Comment by rafaqz** [comment]
Was just running CI, which you also can't trigger 😅

**Pull request merged**
